### ISSUE TITLE
student MNIST code reading + rewrite

### ISSUE THREAD

**Issue by jl749** [jl749/knowledge-distillation-pytorch#1]
## what
read MNIST student model + rewrite in modular format

## why
repo contains deprecated codes such as [Variable](https://pytorch.org/docs/stable/autograd.html#variable-deprecated)

## TODO:
- [x] read the code
- [x] rearrange the code
- [x] add evaluation progress bar (either multiprocessing or tqdm)
